# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.22.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/florrdv/Projects/graphics-engine-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/florrdv/Projects/graphics-engine-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/florrdv/Projects/graphics-engine-cpp/CMakeFiles /Users/florrdv/Projects/graphics-engine-cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/florrdv/Projects/graphics-engine-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/build
.PHONY : engine/fast

easy_image.o: easy_image.cc.o
.PHONY : easy_image.o

# target to build an object file
easy_image.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/easy_image.cc.o
.PHONY : easy_image.cc.o

easy_image.i: easy_image.cc.i
.PHONY : easy_image.i

# target to preprocess a source file
easy_image.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/easy_image.cc.i
.PHONY : easy_image.cc.i

easy_image.s: easy_image.cc.s
.PHONY : easy_image.s

# target to generate assembly for a file
easy_image.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/easy_image.cc.s
.PHONY : easy_image.cc.s

engine.o: engine.cc.o
.PHONY : engine.o

# target to build an object file
engine.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/engine.cc.o
.PHONY : engine.cc.o

engine.i: engine.cc.i
.PHONY : engine.i

# target to preprocess a source file
engine.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/engine.cc.i
.PHONY : engine.cc.i

engine.s: engine.cc.s
.PHONY : engine.s

# target to generate assembly for a file
engine.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/engine.cc.s
.PHONY : engine.cc.s

handlers/2DLsystem.o: handlers/2DLsystem.cc.o
.PHONY : handlers/2DLsystem.o

# target to build an object file
handlers/2DLsystem.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/2DLsystem.cc.o
.PHONY : handlers/2DLsystem.cc.o

handlers/2DLsystem.i: handlers/2DLsystem.cc.i
.PHONY : handlers/2DLsystem.i

# target to preprocess a source file
handlers/2DLsystem.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/2DLsystem.cc.i
.PHONY : handlers/2DLsystem.cc.i

handlers/2DLsystem.s: handlers/2DLsystem.cc.s
.PHONY : handlers/2DLsystem.s

# target to generate assembly for a file
handlers/2DLsystem.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/2DLsystem.cc.s
.PHONY : handlers/2DLsystem.cc.s

handlers/3DLsystem.o: handlers/3DLsystem.cc.o
.PHONY : handlers/3DLsystem.o

# target to build an object file
handlers/3DLsystem.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/3DLsystem.cc.o
.PHONY : handlers/3DLsystem.cc.o

handlers/3DLsystem.i: handlers/3DLsystem.cc.i
.PHONY : handlers/3DLsystem.i

# target to preprocess a source file
handlers/3DLsystem.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/3DLsystem.cc.i
.PHONY : handlers/3DLsystem.cc.i

handlers/3DLsystem.s: handlers/3DLsystem.cc.s
.PHONY : handlers/3DLsystem.s

# target to generate assembly for a file
handlers/3DLsystem.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/3DLsystem.cc.s
.PHONY : handlers/3DLsystem.cc.s

handlers/Intro.o: handlers/Intro.cc.o
.PHONY : handlers/Intro.o

# target to build an object file
handlers/Intro.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/Intro.cc.o
.PHONY : handlers/Intro.cc.o

handlers/Intro.i: handlers/Intro.cc.i
.PHONY : handlers/Intro.i

# target to preprocess a source file
handlers/Intro.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/Intro.cc.i
.PHONY : handlers/Intro.cc.i

handlers/Intro.s: handlers/Intro.cc.s
.PHONY : handlers/Intro.s

# target to generate assembly for a file
handlers/Intro.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/Intro.cc.s
.PHONY : handlers/Intro.cc.s

handlers/Universal.o: handlers/Universal.cc.o
.PHONY : handlers/Universal.o

# target to build an object file
handlers/Universal.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/Universal.cc.o
.PHONY : handlers/Universal.cc.o

handlers/Universal.i: handlers/Universal.cc.i
.PHONY : handlers/Universal.i

# target to preprocess a source file
handlers/Universal.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/Universal.cc.i
.PHONY : handlers/Universal.cc.i

handlers/Universal.s: handlers/Universal.cc.s
.PHONY : handlers/Universal.s

# target to generate assembly for a file
handlers/Universal.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/Universal.cc.s
.PHONY : handlers/Universal.cc.s

handlers/WireFrame.o: handlers/WireFrame.cc.o
.PHONY : handlers/WireFrame.o

# target to build an object file
handlers/WireFrame.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/WireFrame.cc.o
.PHONY : handlers/WireFrame.cc.o

handlers/WireFrame.i: handlers/WireFrame.cc.i
.PHONY : handlers/WireFrame.i

# target to preprocess a source file
handlers/WireFrame.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/WireFrame.cc.i
.PHONY : handlers/WireFrame.cc.i

handlers/WireFrame.s: handlers/WireFrame.cc.s
.PHONY : handlers/WireFrame.s

# target to generate assembly for a file
handlers/WireFrame.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/WireFrame.cc.s
.PHONY : handlers/WireFrame.cc.s

handlers/ZBufferTriangle.o: handlers/ZBufferTriangle.cc.o
.PHONY : handlers/ZBufferTriangle.o

# target to build an object file
handlers/ZBufferTriangle.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/ZBufferTriangle.cc.o
.PHONY : handlers/ZBufferTriangle.cc.o

handlers/ZBufferTriangle.i: handlers/ZBufferTriangle.cc.i
.PHONY : handlers/ZBufferTriangle.i

# target to preprocess a source file
handlers/ZBufferTriangle.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/ZBufferTriangle.cc.i
.PHONY : handlers/ZBufferTriangle.cc.i

handlers/ZBufferTriangle.s: handlers/ZBufferTriangle.cc.s
.PHONY : handlers/ZBufferTriangle.s

# target to generate assembly for a file
handlers/ZBufferTriangle.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/handlers/ZBufferTriangle.cc.s
.PHONY : handlers/ZBufferTriangle.cc.s

ini_configuration.o: ini_configuration.cc.o
.PHONY : ini_configuration.o

# target to build an object file
ini_configuration.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/ini_configuration.cc.o
.PHONY : ini_configuration.cc.o

ini_configuration.i: ini_configuration.cc.i
.PHONY : ini_configuration.i

# target to preprocess a source file
ini_configuration.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/ini_configuration.cc.i
.PHONY : ini_configuration.cc.i

ini_configuration.s: ini_configuration.cc.s
.PHONY : ini_configuration.s

# target to generate assembly for a file
ini_configuration.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/ini_configuration.cc.s
.PHONY : ini_configuration.cc.s

lib/l_parser/l_parser.o: lib/l_parser/l_parser.cc.o
.PHONY : lib/l_parser/l_parser.o

# target to build an object file
lib/l_parser/l_parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/lib/l_parser/l_parser.cc.o
.PHONY : lib/l_parser/l_parser.cc.o

lib/l_parser/l_parser.i: lib/l_parser/l_parser.cc.i
.PHONY : lib/l_parser/l_parser.i

# target to preprocess a source file
lib/l_parser/l_parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/lib/l_parser/l_parser.cc.i
.PHONY : lib/l_parser/l_parser.cc.i

lib/l_parser/l_parser.s: lib/l_parser/l_parser.cc.s
.PHONY : lib/l_parser/l_parser.s

# target to generate assembly for a file
lib/l_parser/l_parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/lib/l_parser/l_parser.cc.s
.PHONY : lib/l_parser/l_parser.cc.s

lib/vector3d/vector3d.o: lib/vector3d/vector3d.cc.o
.PHONY : lib/vector3d/vector3d.o

# target to build an object file
lib/vector3d/vector3d.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/lib/vector3d/vector3d.cc.o
.PHONY : lib/vector3d/vector3d.cc.o

lib/vector3d/vector3d.i: lib/vector3d/vector3d.cc.i
.PHONY : lib/vector3d/vector3d.i

# target to preprocess a source file
lib/vector3d/vector3d.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/lib/vector3d/vector3d.cc.i
.PHONY : lib/vector3d/vector3d.cc.i

lib/vector3d/vector3d.s: lib/vector3d/vector3d.cc.s
.PHONY : lib/vector3d/vector3d.s

# target to generate assembly for a file
lib/vector3d/vector3d.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/lib/vector3d/vector3d.cc.s
.PHONY : lib/vector3d/vector3d.cc.s

util/Color.o: util/Color.cc.o
.PHONY : util/Color.o

# target to build an object file
util/Color.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/Color.cc.o
.PHONY : util/Color.cc.o

util/Color.i: util/Color.cc.i
.PHONY : util/Color.i

# target to preprocess a source file
util/Color.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/Color.cc.i
.PHONY : util/Color.cc.i

util/Color.s: util/Color.cc.s
.PHONY : util/Color.s

# target to generate assembly for a file
util/Color.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/Color.cc.s
.PHONY : util/Color.cc.s

util/Face.o: util/Face.cc.o
.PHONY : util/Face.o

# target to build an object file
util/Face.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/Face.cc.o
.PHONY : util/Face.cc.o

util/Face.i: util/Face.cc.i
.PHONY : util/Face.i

# target to preprocess a source file
util/Face.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/Face.cc.i
.PHONY : util/Face.cc.i

util/Face.s: util/Face.cc.s
.PHONY : util/Face.s

# target to generate assembly for a file
util/Face.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/Face.cc.s
.PHONY : util/Face.cc.s

util/Figure.o: util/Figure.cc.o
.PHONY : util/Figure.o

# target to build an object file
util/Figure.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/Figure.cc.o
.PHONY : util/Figure.cc.o

util/Figure.i: util/Figure.cc.i
.PHONY : util/Figure.i

# target to preprocess a source file
util/Figure.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/Figure.cc.i
.PHONY : util/Figure.cc.i

util/Figure.s: util/Figure.cc.s
.PHONY : util/Figure.s

# target to generate assembly for a file
util/Figure.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/Figure.cc.s
.PHONY : util/Figure.cc.s

util/Line2D.o: util/Line2D.cc.o
.PHONY : util/Line2D.o

# target to build an object file
util/Line2D.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/Line2D.cc.o
.PHONY : util/Line2D.cc.o

util/Line2D.i: util/Line2D.cc.i
.PHONY : util/Line2D.i

# target to preprocess a source file
util/Line2D.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/Line2D.cc.i
.PHONY : util/Line2D.cc.i

util/Line2D.s: util/Line2D.cc.s
.PHONY : util/Line2D.s

# target to generate assembly for a file
util/Line2D.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/Line2D.cc.s
.PHONY : util/Line2D.cc.s

util/Point2D.o: util/Point2D.cc.o
.PHONY : util/Point2D.o

# target to build an object file
util/Point2D.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/Point2D.cc.o
.PHONY : util/Point2D.cc.o

util/Point2D.i: util/Point2D.cc.i
.PHONY : util/Point2D.i

# target to preprocess a source file
util/Point2D.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/Point2D.cc.i
.PHONY : util/Point2D.cc.i

util/Point2D.s: util/Point2D.cc.s
.PHONY : util/Point2D.s

# target to generate assembly for a file
util/Point2D.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/Point2D.cc.s
.PHONY : util/Point2D.cc.s

util/ZBuffer.o: util/ZBuffer.cc.o
.PHONY : util/ZBuffer.o

# target to build an object file
util/ZBuffer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/ZBuffer.cc.o
.PHONY : util/ZBuffer.cc.o

util/ZBuffer.i: util/ZBuffer.cc.i
.PHONY : util/ZBuffer.i

# target to preprocess a source file
util/ZBuffer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/ZBuffer.cc.i
.PHONY : util/ZBuffer.cc.i

util/ZBuffer.s: util/ZBuffer.cc.s
.PHONY : util/ZBuffer.s

# target to generate assembly for a file
util/ZBuffer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/ZBuffer.cc.s
.PHONY : util/ZBuffer.cc.s

util/generators/PlatonicSolids.o: util/generators/PlatonicSolids.cc.o
.PHONY : util/generators/PlatonicSolids.o

# target to build an object file
util/generators/PlatonicSolids.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/generators/PlatonicSolids.cc.o
.PHONY : util/generators/PlatonicSolids.cc.o

util/generators/PlatonicSolids.i: util/generators/PlatonicSolids.cc.i
.PHONY : util/generators/PlatonicSolids.i

# target to preprocess a source file
util/generators/PlatonicSolids.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/generators/PlatonicSolids.cc.i
.PHONY : util/generators/PlatonicSolids.cc.i

util/generators/PlatonicSolids.s: util/generators/PlatonicSolids.cc.s
.PHONY : util/generators/PlatonicSolids.s

# target to generate assembly for a file
util/generators/PlatonicSolids.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/generators/PlatonicSolids.cc.s
.PHONY : util/generators/PlatonicSolids.cc.s

util/generators/Transformations.o: util/generators/Transformations.cc.o
.PHONY : util/generators/Transformations.o

# target to build an object file
util/generators/Transformations.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/generators/Transformations.cc.o
.PHONY : util/generators/Transformations.cc.o

util/generators/Transformations.i: util/generators/Transformations.cc.i
.PHONY : util/generators/Transformations.i

# target to preprocess a source file
util/generators/Transformations.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/generators/Transformations.cc.i
.PHONY : util/generators/Transformations.cc.i

util/generators/Transformations.s: util/generators/Transformations.cc.s
.PHONY : util/generators/Transformations.s

# target to generate assembly for a file
util/generators/Transformations.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/util/generators/Transformations.cc.s
.PHONY : util/generators/Transformations.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... engine"
	@echo "... easy_image.o"
	@echo "... easy_image.i"
	@echo "... easy_image.s"
	@echo "... engine.o"
	@echo "... engine.i"
	@echo "... engine.s"
	@echo "... handlers/2DLsystem.o"
	@echo "... handlers/2DLsystem.i"
	@echo "... handlers/2DLsystem.s"
	@echo "... handlers/3DLsystem.o"
	@echo "... handlers/3DLsystem.i"
	@echo "... handlers/3DLsystem.s"
	@echo "... handlers/Intro.o"
	@echo "... handlers/Intro.i"
	@echo "... handlers/Intro.s"
	@echo "... handlers/Universal.o"
	@echo "... handlers/Universal.i"
	@echo "... handlers/Universal.s"
	@echo "... handlers/WireFrame.o"
	@echo "... handlers/WireFrame.i"
	@echo "... handlers/WireFrame.s"
	@echo "... handlers/ZBufferTriangle.o"
	@echo "... handlers/ZBufferTriangle.i"
	@echo "... handlers/ZBufferTriangle.s"
	@echo "... ini_configuration.o"
	@echo "... ini_configuration.i"
	@echo "... ini_configuration.s"
	@echo "... lib/l_parser/l_parser.o"
	@echo "... lib/l_parser/l_parser.i"
	@echo "... lib/l_parser/l_parser.s"
	@echo "... lib/vector3d/vector3d.o"
	@echo "... lib/vector3d/vector3d.i"
	@echo "... lib/vector3d/vector3d.s"
	@echo "... util/Color.o"
	@echo "... util/Color.i"
	@echo "... util/Color.s"
	@echo "... util/Face.o"
	@echo "... util/Face.i"
	@echo "... util/Face.s"
	@echo "... util/Figure.o"
	@echo "... util/Figure.i"
	@echo "... util/Figure.s"
	@echo "... util/Line2D.o"
	@echo "... util/Line2D.i"
	@echo "... util/Line2D.s"
	@echo "... util/Point2D.o"
	@echo "... util/Point2D.i"
	@echo "... util/Point2D.s"
	@echo "... util/ZBuffer.o"
	@echo "... util/ZBuffer.i"
	@echo "... util/ZBuffer.s"
	@echo "... util/generators/PlatonicSolids.o"
	@echo "... util/generators/PlatonicSolids.i"
	@echo "... util/generators/PlatonicSolids.s"
	@echo "... util/generators/Transformations.o"
	@echo "... util/generators/Transformations.i"
	@echo "... util/generators/Transformations.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

